import type { NextPage } from 'next'
import { Login } from '../sections/Login'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Etcétera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/logo.png" />
      </Head>

      <Login />
    </div>
  )
}

export default Home
